name:                biocad-test-cabal
version:             0.1.0.0
github:              "lupusanay/biocad-test-cabal"
license:             BSD3
author:              "Ilya Kopeshtianski"
maintainer:          "lupusanay@gmail.com"
copyright:           "2020 Ilya Kopeshtianski"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lupusanay/biocad-test#readme>

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - NoMonomorphismRestriction
  - TypeApplications
  - OverloadedStrings
  - TypeFamilies
  - OverloadedLabels
  - GeneralizedNewtypeDeriving

dependencies:
  - base
  - hasbolt
  - text
  - data-default
  - containers
  - mtl
  - either
  - lens
  - generic-lens

library:
  source-dirs: src
  ghc-options:
    - -Wall
